### ISSUE TITLE
Support for social login?

### ISSUE THREAD

**Issue by derek-adair** [inkandfeet/inkshop#8]
Also curious what your thoughts are to this end.  Would this violate any of the principles of this project?

IF this is desirable,  Here are some options with my experience implementing them over the years.

1. [Python Social Auth](https://python-social-auth.readthedocs.io/en/latest/), old, thorough, tried and tested.  Also kind of nice to not be tied directly to django.
2. [Django Allauth](https://github.com/pennersr/django-allauth) is really nice.  However, I had troubles integrating this project w/ django rest [framework](https://www.django-rest-framework.org/) 
3. [Djoser](https://djoser.readthedocs.io/en/latest/) is pretty solid if you want to support a more modern architecture.  (works w/ python social auth). Pairs with something like [simple-jwt](https://github.com/davesque/django-rest-framework-simplejwt) for auth.

**Comment by skoczen** [comment]
Good question!

I'm probably a solid -1 to social login, just because it introduces new attack vectors against user data.  IMO, we should be encouraging a unique auth set for every app, and encourage password managers to mitigate the overhead of managing a ton of logins.

I can be swayed by a compelling case, especially auth from a social project that's built on strong cryptography roots, but things like Facebook and Twitter are probably nonstarters for me.

**Comment by derek-adair** [comment]
Which attack vectors does this open up?

**Comment by skoczen** [comment]
Mostly compromise of the social provider login - either the primary login, or over-granted API access.  Social logins (google, facebook) are the primary phishing targets, and we've seen examples in the wild where external apps have access to data they shouldn't.  By not enabling social login, we reduce the exposed attack surface.

I'd be open to reconsidering, but I'd need a compelling use-case that suggests social login is a significant feature that outweighs the costs.

**Comment by derek-adair** [comment]
>I'd be open to reconsidering, but I'd need a compelling use-case that suggests social login is a significant feature that outweighs the costs.

Probably wont find one for this.  The main benefit to social login, in my eyes, is the ease of the signup flow.  Upon further thinking, inkshop doesn't really care about that.  Closing for this reason.
